#### Relying Party properties

# The relying party ID. Must be a valid domain string. A public key credential is only registered and valid for a single relying party ID.
idp.authn.webauthn.relyingPartyId = idp.example.com

# A human-palatable name of the Relying Party
idp.authn.webauthn.relyingPartyName = Shinshu IdP PoC

# Allow any port on that origin
#idp.authn.webauthn.allowOriginPort = false

# Allow any subdomain of that origin
#idp.authn.webauthn.allowOriginSubdomain = false

# Generic flow properties to adjust behavior
#idp.authn.webauthn.order = 1000
#idp.authn.webauthn.forcedAuthenticationSupported = true
# The list below should be changed to reflect whatever locally- or
# community-defined values are appropriate to represent WebAuthn. It is
# strongly advised that the value not be specific to WebAuthn or any
# particular technology to avoid lock-in.
idp.authn.webauthn.supportedPrincipals = \
    saml2/http://example.org/ac/classes/mfa, \
    saml1/http://example.org/ac/classes/mfa
# Override to keep the WebAuthnContext around
#idp.authn.webauthn.removeAfterValidation = true

# An override of origins this RP allows in a responses from an authenticator
#idp.authn.webauthn.origins = 

# The storage service to use as a credential repository
#idp.authn.webauthn.StorageService = shibboleth.StorageService
# Enable or disable the credential repository cache
#idp.authn.webauthn.StorageService.cache.enable = true
# Set the expires after last access time on the cache
#idp.authn.webauthn.StorageService.cache.expireAfterAccess = PT60M
# The JDBC credential repository accelerator to use, only to be enabled if you are using a JDBC storage service with a compatible RDMS
#idp.authn.webauthn.StorageService.jdbcAccelerator = WebAuthnJDBCAccelerator
#idp.authn.webauthn.StorageService.jdbcAccelerator.defaultType = QUERY

# Which type of flow is supported? Usernameless (true) or passwordless (false)
#idp.authn.webauthn.usernameless.enabled = false

# Allow this flow to act as a second factor. 
idp.authn.webauthn.2fa.enabled = true

# Which previous factors are acceptable to allow the WebAuthn flow to act as a second factor of authentication e.g. authn/Password.
idp.authn.webauthn.2fa.allowedPreviousFactors = authn/Password

# Force second factor even if no acceptable previous factors ran
#idp.authn.webauthn.2fa.forceSecondFactorFlow = false

# The bean name of the username lookup strategy. By default, this comes from the principal name established by the first factor.
#idp.authn.webauthn.2fa.username.strategy = shibboleth.authn.WebAuthn.CanonicalUsernameLookupStrategy

# Should an event be built if there are no credentials found? Only applicable to 2fa authentication.
#idp.authn.webauthn.2fa.signalEventOnNoCredentials = false
#idp.authn.webauthn.2fa.noCredentialsEventId = NoRegisteredWebAuthnCredentials

# Should we update an authenticators signature counter inside the credential repository after each successful authentication?  
#idp.authn.webauthn.updateSignatureCount = true

# Should the last authentication time for a credential be updated after each successful authentication?  
#idp.authn.webauthn.updateLastUsedTime = false

# Should an event be built if there are no credentials found? Only applicable to passwordless authentication.
#idp.authn.webauthn.passwordless.signalEventOnNoCredentials = false
#idp.authn.webauthn.passwordless.noCredentialsEventId = NoRegisteredWebAuthnCredentials

# Should a custom event be built if the userHandle supplied by the authenticator during authentication is not related
# to any registered credentials? 
#idp.authn.webauthn.signalEventOnNoCredentialsRegisteredForUserHandle = false
#idp.authn.webauthn.userHandleNoRegisteredCredentialsEventId = NoCredentialsRegisteredForUserHandle

# Basic transformations that should be applied to the username that is collected as part of the passwordless flow
#idp.authn.webauthn.passwordless.username.uppercase = false
#idp.authn.webauthn.passwordless.username.lowercase = false
#idp.authn.webauthn.passwordless.username.trim = false

# Field name settings for various input views
#idp.authn.webauthn.ssoBypassFieldName = donotcache
#idp.authn.webauthn.usernameFieldName = j_username
#idp.authn.webauthn.publicKeyCredentialAssertionFieldName = publicKeyCredential

# The ID of the bean that supplies the c14n flows that are applied to the username entered during the passwordless flow
#idp.authn.webauthn.passwordless.c14n.postUsernameFlows = shibboleth.PostLoginSubjectCanonicalizationFlows

# Enable the credential filter policy engine for passwordless and second factor flows. This runs before the user has had the opportunity to authenticate.
#idp.authn.webauthn.credential.filter.policy.enabled = false
# Set the credential policies to use, defaults to a chained set of policies
#idp.authn.webauthn.credential.filter.policy = shibboleth.authn.WebAuthn.ChainedCredentialPolicy
# If there are no credentials left after filtering, the following non-proceed event is signalled
#idp.authn.webauthn.credential.filter.policy.noCredentialsEventId = NoCredentials

# Enable the credential policy engine. This runs after the user has chosen a key to authenticate with and the assertion response returned to the IdP.
#idp.authn.webauthn.credential.policy.enabled = false
# Set the credential policies to use, defaults to a chained set of policies
#idp.authn.webauthn.credential.policy = shibboleth.authn.WebAuthn.ChainedCredentialPolicy
# When using the default chained policy, which policy list should we use?
#idp.authn.webauthn.credential.policy.chainedlist = shibboleth.authn.WebAuthn.ChainedCredentialPolicyList
# When using the default chained list of policies; list authenticators (by attestation GUIDs (AAGUID)) to tag as only allowed for second factor authentication
#idp.authn.webauthn.authenticator.policy.secondFactorOnlyAuthenticators = 

# Audit
#idp.authn.webauthn.audit.enabled = false
#idp.authn.webauthn.audit.format = %a|%T|%SP|%I|%s|%AF|%CV|%u|%WebAuthnUID|%WebAuthnUV|%WebAuthnFM|%tu|%AR|%UA
#idp.authn.webauthn.audit.category = Shibboleth-Audit.WebAuthn

# Debugging

# Display debug information about the registration and authentication ceremony on their respective views?
#idp.authn.webauthn.ui.debug = false
